-- TAM Mobile — central cloud database for the three phones.
-- Run in Supabase SQL Editor after creating a project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null check (role in ('organization_secretary','finance_secretary','regional_captain','administrator')),
  created_at timestamptz not null default now()
);

create table if not exists public.districts (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.institutions (
  id uuid primary key default gen_random_uuid(),
  district_id uuid not null references public.districts(id) on delete restrict,
  name text not null,
  total_staff integer not null default 0,
  other_union_members integer not null default 0,
  non_union_staff integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(district_id, name)
);

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  district_id uuid not null references public.districts(id) on delete restrict,
  institution_id uuid not null references public.institutions(id) on delete restrict,
  name text not null,
  guide text,
  card_no text,
  phone text,
  notes text,
  membership_status text not null default 'active',
  status_date date,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscription_payments (
  id uuid primary key default gen_random_uuid(),
  member_id uuid references public.members(id) on delete restrict,
  member_name text,
  financial_guide text,
  card_no text,
  payment_year integer not null,
  payment_month integer,
  payment_date date,
  subscription_amount numeric not null default 0,
  card_fee numeric not null default 0,
  total_amount numeric not null default 0,
  source text,
  source_name text,
  payment_method text not null default 'cash' check (payment_method in ('cash','banking_app','masrifi','bankily','sedad','bim_bank')),
  payment_reference text,
  matched_by text,
  direct_to_executive boolean not null default false,
  import_batch_id text,
  row_hash text unique,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  action text not null,
  entity text not null,
  entity_id text,
  details text,
  created_at timestamptz not null default now()
);

create or replace function public.current_role() returns text
language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

alter table public.profiles enable row level security;
alter table public.districts enable row level security;
alter table public.institutions enable row level security;
alter table public.members enable row level security;
alter table public.subscription_payments enable row level security;
alter table public.audit_log enable row level security;

-- Profiles: a user may read only their own profile.
drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self on public.profiles for select using (id = auth.uid());

-- Reference data readable by all three phones; only organization/admin may change it.
drop policy if exists districts_select on public.districts;
create policy districts_select on public.districts for select using (auth.uid() is not null);
drop policy if exists districts_write on public.districts;
create policy districts_write on public.districts for all using (public.current_role() in ('organization_secretary','administrator')) with check (public.current_role() in ('organization_secretary','administrator'));

drop policy if exists institutions_select on public.institutions;
create policy institutions_select on public.institutions for select using (auth.uid() is not null);
drop policy if exists institutions_write on public.institutions;
create policy institutions_write on public.institutions for all using (public.current_role() in ('organization_secretary','administrator')) with check (public.current_role() in ('organization_secretary','administrator'));

-- Members: organization manages; finance can read only for selecting a member; captain can read for list export.
drop policy if exists members_select on public.members;
create policy members_select on public.members for select using (auth.uid() is not null);
drop policy if exists members_insert on public.members;
create policy members_insert on public.members for insert with check (public.current_role() in ('organization_secretary','administrator'));
drop policy if exists members_update on public.members;
create policy members_update on public.members for update using (public.current_role() in ('organization_secretary','administrator')) with check (public.current_role() in ('organization_secretary','administrator'));
drop policy if exists members_delete on public.members;
create policy members_delete on public.members for delete using (public.current_role() in ('organization_secretary','administrator'));

-- Payments: organization can add/correct/delete; finance can INSERT only; captain has no payment access.
drop policy if exists payments_select on public.subscription_payments;
create policy payments_select on public.subscription_payments for select using (public.current_role() in ('organization_secretary','administrator'));
drop policy if exists payments_insert on public.subscription_payments;
create policy payments_insert on public.subscription_payments for insert with check (public.current_role() in ('organization_secretary','finance_secretary','administrator'));
drop policy if exists payments_update on public.subscription_payments;
create policy payments_update on public.subscription_payments for update using (public.current_role() in ('organization_secretary','administrator')) with check (public.current_role() in ('organization_secretary','administrator'));
drop policy if exists payments_delete on public.subscription_payments;
create policy payments_delete on public.subscription_payments for delete using (public.current_role() in ('organization_secretary','administrator'));

-- Audit is append-only for authenticated clients; reading is restricted to organization/admin.
drop policy if exists audit_insert on public.audit_log;
create policy audit_insert on public.audit_log for insert with check (auth.uid() = actor_id);
drop policy if exists audit_select on public.audit_log;
create policy audit_select on public.audit_log for select using (public.current_role() in ('organization_secretary','administrator'));
